Contact_form: Mobile_version
BenjaminMatembe/Portfolio pull request #4
Opened 2023-03-28 16:27 UTC by BenjaminMatembe

On this feature we added:

- HTML layout
- CSS designs
- form Validation

2023-03-28 17:29 UTC, shella12 requested changes
Hi @BenjaminMatembe , 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights

- All linters passed ✅ 
- Professional README.md ✅   
- Descriptive pull request ✅ 
- Great design implementation ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 17:29 UTC, shella12 commented on index.html
> +    </ul>
- [ ] Please make sure that all form fields should have `required` attribute including `textarea` as it is the [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md#project-requirements) of the project that a user should not be able to submit the form if one or more of the fields is empty

> **Project Requirements**
>
>  Make sure that:
> - A user cannot submit the form if one or more of the fields is empty.

2023-03-28 17:29 UTC, shella12 commented on styles.css
> +}
- [ ] The contact form heading text in the [figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1-1471&t=F1n7sMh4ZV6XntRp-0) is aligned in the centre of the container. Please make sure your heading also looks identical to that in the figma design as it is the [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md#project-requirements) that:

> You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

_Hint: Try adding `padding` or `margin` around the text_

your design:

<img width="366" alt="Screenshot 2023-03-28 at 10 09 28 PM" src="https://user-images.githubusercontent.com/44798044/228316904-7b8bca17-a942-4c79-a1a3-ca162c78ce3f.png">

figma design:

<img width="435" alt="Screenshot 2023-03-28 at 10 11 49 PM" src="https://user-images.githubusercontent.com/44798044/228316969-0ab9e5a9-3e53-4226-b6c0-721a8b8b6968.png">

2023-03-28 17:29 UTC, shella12 commented on styles.css
> +
- [ ] According to the project requirements we must stick to the [figma design template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1-1471&t=1yfXx6yoiCqxC0tL-0) and make sure our design looks identical to figma. So please make sure your design also includes all the elements present in the figma design as your design is missing a line under the footer icons

Figma design

<img width="435" alt="Screenshot 2023-03-28 at 10 12 01 PM" src="https://user-images.githubusercontent.com/44798044/228319131-edbbb126-35b2-484d-ac01-563270b0c6d3.png">


Your design:


<img width="417" alt="Screenshot 2023-03-28 at 10 23 08 PM" src="https://user-images.githubusercontent.com/44798044/228319261-2de4415d-fac2-4df8-bd1b-01f9292e6650.png">

2023-03-28 17:29 UTC, shella12 commented on styles.css
> +}
- [ ] [OPTIONAL] It would be better if you remove the outline from the input fields or add a little padding in the input fields because when the input field is focused the outline makes your input really narrow.

<img width="396" alt="Screenshot 2023-03-28 at 10 09 48 PM" src="https://user-images.githubusercontent.com/44798044/228320011-4f5ca53c-81bf-4016-acbc-d5a7f8f2dbcb.png">

2023-03-28 19:01 UTC, huseyinbiyik approved these changes
Hi team,

## ✔️ Status: APPROVED 🏆 🎉 🎊

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/wZjlCH43M3M0U/giphy.gif)



## Highlights
- Pair work 👍 👍 
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- PR description is descriptive 📝
- Great implementation of the requested changes of previous reviewers 🕸️

## Optional suggestions

- Please don't disable linters on your CSS file(line 4 on styles.css). It is better to understand the linter error before your project getting start to complex. You can solve them using more classes for specific elements instead of selecting as group or move the CSS declarations according their priorities. In other case, probably next reviewer will ask for remove it.
There are a few reasons for using linters:
Catching syntax errors is more efficient. There is no need to debug simple mistakes like typos - the linter does it for you.
The entire codebase looks like written by one person.
Programmers can focus on solving problems, instead of cleaning up the code.

- Since it is not a template and a proper README, you can rename your heading below as Benjamin's Portfolio. 👍  It will look much better and professional 👍 

<img width="515" alt="Screenshot 2023-03-28 at 9 53 30 PM" src="https://user-images.githubusercontent.com/25887253/228340342-3fa57de7-3326-495f-8438-abb1afced2c7.png">

-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, 
👌"Add logo to navigation bar"
👌"Fix close button functionality on mobile navbar"
❌ "Added logo to navigation bar"
❌ "Added HTML" 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 19:27 UTC, merged

2023-05-30 13:18 UTC, BenjaminMatembe commented
Hi @huseyinbiyik Thank you for the advise about the commit messages.